name: Build

on:
  workflow_run:
    workflows: [ Test ]
    branches: [ master ]
    types: [ completed ]

  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Assemble
        run: ./gradlew :app:assembleRelease

      - name: Deploy apk
        uses: actions/upload-artifact@v3
        with:
          name: ticTacToeWear
          path: app/build/outputs/apk/release/app-release.apk
          retention-days: 2
