name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_run:
    workflows: [ Lint ]
    types: [ completed ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Change wrapper permission
        run: chmod +x ./gradlew

      - name: Run unit test
        run: ./gradlew :app:testReleaseUnitTest
